---
# tasks file for graylog
- name: Download Graylog
  get_url: "https://packages.gralog2.org/repo/packages/graylog-{{new_version}}-repository_latest.deb"
  dest: /ipswitch/graloylog-repo.deb
  state: present

- name: Install Graylog Repo
  apt:
   deb: /ipswitch/graylog-repo.deb
   state: present
  become: yes

- name: Upgrade Graylog Server
  apt:
   name: graylog-server
   state: latest
  notify: Restart Graylog
  become: yes

